# Generated by Django 5.2 on 2025-05-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_microcontroller_identifier_alter_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microcontroller',
            name='ward',
            field=models.ForeignKey(blank=True, help_text='Set this only if the microcontroller is assigned for ward readings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microcontrollers', to='data_management.ward'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.IntegerField(blank=True, help_text='National ID or equivalent identification number', null=True, unique=True),
        ),
    ]
