# Generated by Django 5.2 on 2025-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_microcontroller_ward_alter_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardreading',
            name='light_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
